## Run saveFreqBandsM.py
#PBS -l nodes=1:ppn=1
#PBS -l mem=1GB
#PBS -l walltime=06:00:00
#PBS -S /bin/bash
#PBS -N comps11_20
#PBS -o comps11_20_out.txt
#PBS -e comps11_20_err.txt


source /home/reo000/myconda
conda activate py39dc2

cd /home/reo000/MSME/Site-specific-multiple-stressor-manuscript-code-Can/code/Tools/Tools
for i in {11..20}; do `python OAPBuoyComp.py run1CompScenM $i CanESM5CanOE_1975_2022_monthly` ; done
echo 'done'
