## Run saveFreqBandsM.py
#PBS -l nodes=1:ppn=1
#PBS -l mem=1GB
#PBS -l walltime=06:00:00
#PBS -S /bin/bash
#PBS -N comps0_10
#PBS -o comps0_10_out.txt
#PBS -e comps0_10_err.txt


source /home/reo000/myconda
conda activate py39dc2

cd /home/reo000/MSME/Site-specific-multiple-stressor-manuscript-code-Can/code/Tools/Tools
for i in {0..10}; do `python OAPBuoyComp.py run1CompScenMSat $i CanESM5CanOE_1975_2022_monthly` ; done
echo 'done'
